baseURL = "https://ShenYimingDaDa.github.io"
DefaultContentLanguage = "zh-hant" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-hant" # Language code for this content, supports: en, fr, zh, zh-hant
title = "摆人日寄"
copyright = "This is a customized copyright."

# googleAnalytics = "UA-123-45"
[markup]


[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "perldoc"
tabWidth = 4

[params]
subtitle = "啊对对对。"
enableGitalk = false
favicon = "static/images/bird.jpg"
enableReadingTime = true
# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description" # will set 'og:description'

[params.gitalk]
owner = "ShenYimin"
repo = "BlogComment"
client_id = "87b383f0bc03d41e07fe"
client_secret = "ebd8d74511e37d50021fa2decc3d65f19cbe5445"

[taxonomies]
tag = "tags"
category = "categories"

[params.utterances]
repo = "your repo"
term = "[ENTER TERM HERE]"
label = "your label"
theme = "github-light"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2

[[menu.main]]
url = "/tags"
name = "标签"
weight = 3

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
